spring.application.name=pg_pritani
spring.datasource.url=jdbc:postgresql://localhost:5435/pg_pritani_java
spring.datasource.username=postgres
spring.datasource.password=MUHLESS717GG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true